name: teleport
version: '1.0'
main: me.can.teleport.Teleport
api-version: '1.21'
commands:
  tp:
    description: isinlamaya yariyor.
    aliases:
      - isinlan
  tptoggle:
    description: Teleportunuzu kapatıp açmaya yarar.
    aliases:
      - tpt
